export const departure = 'place of departure';
export const arrival = 'place of arrival';
export const select = 'find';
export const our_flights = 'our flights';
export const PERSON = 'person';
export const PILOT = 'pilot';
export const WINDOW = 'window';
export const DOOR = 'door';
export const BOTTOM = 'bottom';
export const MARK_YOUR_SEATS = 'mark your seats';
export const VACANT_SEATS = 'vacant seats';
export const YOUR_SELECT = 'your select';
export const RESERVED_SEAT = 'reserved seat';
export const TOTAL_PRICE = 'total price:';
export const SELECTED_SEATS = 'selected seats:';
export const PRICE_FOR_SEATS = 'price for seats:';
export const ORDER = 'order';
export const HOME = 'home';
export const NO_SEATS =
  'Note all seats on this flight are occupied please return to the main page button below';
export const ORDER_CONFIRMATION = 'order confirmation';
export const BACK = 'back';
export const ERROR = 'error';
export const MODAL_ORDER_ERROR_MESSAGE = 'You not select free seat';
export const CLOSE = 'close';
export const PASSANGER = 'passanger';
export const SEAT = 'seat'
export const DEPARTURE = 'departure'
export const ARRIVAL = 'arrival'
