export const departure = 'place of departure';
export const arrival = 'place of arrival';
export const select = 'find';
export const our_flights = 'our flights';
export const PERSON = 'person';
export const PILOT = 'pilot';
export const WINDOW = 'window';
export const DOOR = 'door';
export const BOTTOM = 'bottom';
export const MARK_YOUR_SEATS = 'mark your seats';
export const VACANT_SEATS = 'vacant seats';
export const YOUR_SELECT = 'your select';
export const RESERVED_SEAT = 'reserved seat';
export const TOTAL_PRICE = 'total price:';
export const SELECTED_SEATS = 'selected seats:';
export const PRICE_FOR_SEATS = 'price for seats:';
export const ORDER = 'order';
export const HOME = 'home';
export const NO_SEATS =
  'Note all seats on this flight are occupied please return to the main page button below';
export const ORDER_CONFIRMATION = 'order confirmation';
export const BACK = 'back';
export const ERROR = 'error';
export const MODAL_ORDER_ERROR_MESSAGE = 'You not select free seat';
export const CLOSE = 'close';
export const PASSANGER = 'passanger';
export const SEAT = 'seat'
export const DEPARTURE = 'departure'
export const ARRIVAL = 'arrival'
export const YOUR_ORDERS = 'your order';
export const SUBMIT = 'submit'
export const FLY_INFORMATION = 'fly information'
export const NEXT = 'next'
export const FIRST_NAME = 'first name'
export const SECOND_NAME = 'second name'
export const PHONE_NUMBER = 'phone number'
export const FIELDS = 'please fill in all fields';
export const SUCCESS = 'success'
export const SUCCESS_MODAL_MESSAGE =
  'Thank you for filling in the form. You can continue on';
  export const END_MESSAGE = 'thank you for using our services';
export const DURATION = 'duration'
export const PRICE = 'price'
export const FREE_SEATS = 'free_seats'
export const SELECTS = 'selects'
export const FILTER_ERROR = 'No flights available';
export const SEATS = 'seats'
export const FORM_NAME = 'The name is not a number';
export const FORM_NUMBER = 'Must be a number';
export const TO_SHORT = 'to short'
export const TO_LONG = 'to long'
export const REQUIRED = 'required';
export const PERSON_INFO = 'person info'
export const PERSON_TRAVEL = 'person travel'
